target_path: neural-cellular-automata/data/chest.png
model_path: neural-cellular-automata/models/chest/L2/chest_sobel_damage.pt
device: mps
iterations: 1000
learning_rate: 0.002
img_size: 28
padding: 0
n_channels: 16
batch_size: 8
pool_size: 1024
filter: sobel
loss: L2
damage: True