target_path: neural-cellular-automata/data/chest.png
model_path: neural-cellular-automata/models/chest/L2/chest_sobel_damage.pt
ani_path: neural-cellular-automata/animations/chest/L2/chest_sobel_damage.gif
iterations: 500
img_size: 28
padding: 0
n_channels: 16
filter: sobel
loss: L2
damage: True